### ISSUE TITLE
1.12.2 "ModCrash" ServerThread exception.

### ISSUE THREAD

**Issue by I2pRandom** [Mrbt0907/Weather2-Remastered#192]
**Describe the bug**
While Loading world the following error occured without a crash. 

**To Reproduce**
Unknown, occured while loading world.

**Logs and/or Screenshots**
```
Exception in thread "Server thread" 
[15:22:59] [Server thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Weather 2 - Remastered (weather2remaster)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: Caused by: java.lang.NullPointerException
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.mrbt0907.weather2.Weather2.serverStop(Weather2.java:119)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:852)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:508)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1899)
[15:22:59] [Server thread/INFO] [STDERR]: [net.minecraftforge.fml.common.EnhancedRuntimeException:printStackTrace:92]: 	at java.lang.Thread.run(Thread.java:750)
```
<details>
<summary>Mods</summary>
E:\0Games\Minecraft\Instances\1.12.2\.minecraft\mods>tree /f
Folder PATH listing for volume HDD_Games
Volume serial number is 422F-3439
E:.
│   !configanytime-3.0.jar
│   !mixinbooter-9.1.jar
│   !Red-Core-MC-1.8-1.12-0.6-Dev-3.jar
│   .index.7z
│   ActuallyAdditions-1.12.2-r152.jar
│   actuallycomputers-2.2.0.jar
│   AdChimneys-1.12.2-3.5.16.0-build.0654.jar
│   AdHooks-1.12.2-3.3.1.0-build.0626.jar
│   AdPother-1.12.2-1.2.25.0-build.0673.jar
│   AdvancedRocketry-1.12.2-2.0.0-17.jar
│   AE-Net-Vis-Tool-1.12.2-1.0.3.0-universal.jar
│   ae2-uel-v0.56.4.jar
│   ae2stuff-1.12.2-0.9.jar
│   AE2WTLib-1.12.2-1.0.34.jar
│   aether-1.12.2-v1.5.4.0.jar
│   aether_baubles-1.1.jar
│   agricraft-2.12.0-1.12.2-b2.jar
│   alchemistry-1.12.2-42.jar
│   Alfheim-1.3.jar
│   alib-1.0.12.jar
│   alternatingflux-0.12.2-2.jar
│   AmbientEnvironment-1.0.2.jar
│   AmbientSounds_v3.1.5_mc1.12.2.jar
│   anvilpatch-1.1.1.jar
│   Apotheosis-1.12.2-1.12.5.jar
│   AppleSkin-mc1.12-1.0.14.jar
│   Aquaculture-1.12.2-1.6.8.jar
│   architecturecraft-1.12-3.108.jar
│   Armourers-Workshop-1.12.2-0.51.0.jar
│   ascendedroads-1.12.2-1.0.jar
│   AsmodeusCore-1.12.2-1.0.1.jar
│   astikorcarts-1.12.2-0.1.2.8.jar
│   astralsorcery-1.12.2-1.10.27.jar
│   AutoRegLib-1.3-32.jar
│   BattleTowers-1.12.2.jar
│   Baubles-1.12-1.5.2.jar
│   bdlib-1.14.4.1-mc1.12.2.jar
│   betteranimalsplus-1.12.2-9.0.1.jar
│   betterbiomeblend-1.12.2-1.1.7-forge.jar
│   BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
│   BetterMineshaftsForge-1.12.2-2.2.1.jar
│   BetterNetherRotN-1.12.2-0.2.0.0.jar
│   binnie-mods-1.12.2-2.5.1.210.jar
│   BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
│   BloodMagic-1.12.2-2.4.3-105.jar
│   blue_skies-1.12.2-v1.1.3.jar
│   Bookshelf-1.12.2-2.3.590.jar
│   Botania r1.10-364.4.jar
│   Bountiful Baubles-1.12.2-0.1.8.jar
│   Bountiful-1.12.2-2.2.3.jar
│   BrandonsCore-1.12.2-2.4.20.162-universal.jar
│   buildcraft-all-7.99.24.8.jar
│   BuildingGadgets-2.8.4.jar
│   calculator-1.12.2-5.0.12-15.jar
│   carryon-1.12.2-1.12.7.23.jar
│   castle_dungeons-2.2p1-1.12.2-forge.jar
│   catwalks-1.12.2-4.0.45.jar
│   cc-tweaked-1.12.2-1.89.2.jar
│   censoredasm5.20.jar
│   ChickenChunks-1.12.2-2.4.2.74-universal.jar
│   Clumps-3.1.2.jar
│   CodeChickenLib-1.12.2-3.2.3.358-universal.jar
│   CoFHCore-1.12.2-4.6.6.1-universal.jar
│   CoFHWorld-1.12.2-1.4.0.1-universal.jar
│   comforts-1.12.2-1.4.1.3.jar
│   compactmachines3-1.12.2-3.0.18-b278.jar
│   Computronics-1.12.2-1.6.6.192-rc-beta-5.jar
│   Controlling-3.0.12.2.jar
│   coroutil-1.12.1-1.2.37.jar
│   CreativeCore_v1.10.62_mc1.12.2.jar
│   Cucumber-1.12.2-1.1.3.jar
│   CustomNPCs_1.12.2-(05Jul20).jar
│   cyberware-1.12.2-0.2.11.29.jar
│   CyclopsCore-1.12.2-1.6.7.jar
│   DarkUtils-1.12.2-1.8.230.jar
│   deepresonance-1.12-1.8.0.jar
│   DimensionalDoors-1.12.2-3.0.12.jar
│   DivineRPG-1.7.1.jar
│   DoggyTalents-1.12.2-1.15.1.6.jar
│   Draconic-Additions-1.12.2-1.17.0.45-universal.jar
│   Draconic-Evolution-1.12.2-2.3.28.354-universal.jar
│   durabilitytooltip-1.1.5-forge-mc1.12.jar
│   ElecCore-1.12.2-1.9.453.jar
│   ElevatorMod-1.12.2-1.3.14.jar
│   EmbersRekindled-1.19.jar
│   EnderStorage-1.12.2-2.4.6.137-universal.jar
│   energyconverters_1.12.2-1.3.7.30.jar
│   entityculling-1.12.2-1.6.3.jar
│   environmentaltech-1.12.2-2.0.20.1.jar
│   etlunar-1.12.2-2.0.20.1.jar
│   EvilCraft-1.12.2-0.10.78.jar
│   ExtraPlanets-1.12.2-0.7.7.jar
│   extrautils2-1.12-1.9.9.jar
│   ExtremeReactors-1.12.2-0.4.5.68.jar
│   FamiliarFauna-1.12.2-1.0.11.jar
│   forbidden_arcanus-1.12.2-1.1.4.jar
│   forestry_1.12.2-5.8.2.422.jar
│   ForgeEndertech-1.12.2-4.5.6.1-build.0648.jar
│   Forgelin-Continuous-1.9.23.2.jar
│   ForgeMultipart-1.12.2-2.6.2.83-universal.jar
│   furniture-6.3.2-1.12.2.jar
│   fusion-1.1.1-forge-mc1.12.jar
│   GalacticComputers-1.0.0.jar
│   Galacticraft-1.12.2-4.0.6.jar
│   GalaxySpace-1.12.2-2.1.3.jar
│   gendustryjei-1.0.2.jar
│   Geolosys-1.12.2-3.0.9.jar
│   grappling_hook_mod-1.12.2-v13.jar
│   Guide-API-1.12-2.1.8-63.jar
│   guns-0.15.3-1.12.2.jar
│   hbm-1.8.4a-G.jar
│   HeatAndClimateLib_1.12.2-3.9.3.jar
│   HeatAndClimateMod_1.12.2-3.9.11.jar
│   Helicopter_Pack-2.8.0_1.jar
│   Highlighter-1.12.2-forge-1.1.7.jar
│   iceandfire-1.9.1-1.12.2.jar
│   iChunUtil-1.12.2-7.2.2.jar
│   Immersive Energy-1.12.2-0.5.5.jar
│   ImmersiveCables-1.12.2-1.3.2.jar
│   ImmersiveEngineering-0.12-98.jar
│   immersivepetroleum-1.12.2-1.1.10.jar
│   ImmersivePosts-0.2.1.jar
│   ImprovedMobs-1.12.2-1.6.10.jar
│   incontrol-1.12-3.9.18.jar
│   industrialcraft-2-2.8.222-ex112.jar
│   industrialforegoing-1.12.2-1.12.13-237.jar
│   infinitylib-1.12.1.jar
│   InventoryHUD-1.12.2.forge-3.4.4.jar
│   InventoryNeko-0.2.0.jar
│   InventoryTweaks-1.64+dev.151.jar
│   IronBackpacks-1.12.2-3.0.8-12.jar
│   ironchest-1.12.2-7.0.72.847.jar
│   ItemBlacklist-1.4.3.jar
│   IvToolkit-1.3.3-1.12.jar
│   jeiintegration_1.12.2-1.6.0.jar
│   jei_1.12.2-4.16.1.1012.jar
│   JEROreIntegration-1.12.2-1.1.0.jar
│   journeymap-1.12.2-5.7.1p2.jar
│   JustEnoughResources-1.12.2-0.9.3.203.jar
│   lava_walker-1.12.2-0.5.2.jar
│   LegendaryTooltips-1.12.2-1.1.10.jar
│   LibraryEx-1.12.2-1.2.2.jar
│   LibVulpes-1.12.2-0.4.2-25-universal.jar
│   llibrary-1.7.20-1.12.2.jar
│   LogUnSpam-1.0-1.12.jar
│   lootr-1.12.2-0.6.2.jar
│   lost-aether-content-1.12.2-1.0.2.jar
│   lostcities-1.12-2.0.22.jar
│   LucraftCore-1.12.2-2.4.17.jar
│   lycanitesmobs-1.12.2-2.0.8.9.jar
│   Magneticraft_1.12-2.8.5-dev.jar
│   mahoutsukai-1.12.2-v1.19.55.jar
│   Mantle-1.12-1.3.3.55.jar
│   MapFrontiers-1.12.2-1.5.1.jar
│   marytts-runtime-5.2-jar-for-computronics.jar
│   MCA-1.12.2-6.1.0-universal.jar
│   mcefremasterd-1.12.2-1.21b.jar
│   mcjtylib-1.12-3.5.4.jar
│   MCTImmersiveTechnology-1.12.2-1.9.102.jar
│   mcw-bridges-1.0.6b-mc1.12.2.jar
│   mcw-doors-1.0.3-mc1.12.2.jar
│   mcw-fences-1.0.0-mc1.12.2.jar
│   mcw-furniture-1.0.1-mc1.12.2beta.jar
│   mcw-paintings-1.0.5-1.12.2forge.jar
│   mcw-roofs-1.0.2-mc1.12.2.jar
│   mcw-trapdoors-1.0.3-mc1.12.2.jar
│   mcw-windows-1.0.0-mc1.12.2.jar
│   Mekanism-Community-Edition-1.12.2-9.12.8-ALL.jar
│   millenaire-8.1.2.jar
│   Mine and Slash-1.12.2-1.9.7.jar
│   minecolonies-1.12.2-0.11.841-BETA-universal.jar
│   MJRLegendsLib-1.12.2-1.2.1.jar
│   MmmMmmMmmMmm-1.12-1.14.jar
│   MobGrindingUtils-0.3.13.jar
│   modelloader-1.1.7.jar
│   Modern-Warfare-Cubed-0.1.5.jar
│   Modern_Ruins_Pack_1.12.2_2.5.4(chisel).jar
│   ModularPowersuits-1.12.2-1.1.048.jar
│   moremystcraft-1.12.2-1.0.0.jar
│   morepaintings-paintings-1.12.2-5.0.1.2.jar
│   Morpheus-1.12.2-3.5.106.jar
│   MouseTweaks-2.10.1-mc1.12.2.jar
│   MrTJPCore-1.12.2-2.1.4.43-universal.jar
│   MS Auto-Compat 1.12.2-1.0.7.jar
│   MTR-1.12.2-alpha-test-0.0.1.jar
│   mystcraft-1.12.2-0.13.7.06.jar
│   mystcraft_info-1.12.2-1.0.5.0.jar
│   MysticalAgradditions-1.12.2-1.3.2.jar
│   MysticalAgriculture-1.12.2-1.7.5.jar
│   mystlibrary-1.12.2-0.0.3.2.jar
│   natura-1.12.2-4.3.2.69.jar
│   NaturesCompass-1.12.2-1.8.5-forge.jar
│   NetherEx-1.12.2-2.2.5.jar
│   NiftyBlocks-1.21.jar
│   NonConflictKeys-Forge-1.12.2-1.0.0.jar
│   NovamTerram-7.3.6.3.jar
│   NuclearCraft-2o.6.2-1.12.2.jar
│   nukejndilookupfromlog4j-1.0.0.jar
│   Numina-1.12.2-1.1.049.jar
│   obfuscate-0.4.2-1.12.2.jar
│   OpenBlocks-1.12.2-1.8.1.jar
│   OpenComputers-MC1.12.2-1.8.5+179e1c3.jar
│   OpenGlider-1.12.1-1.1.0.jar
│   OpenLights-MC1.12.2-0.1.0.8.jar
│   OpenLightsController-1.0.1.jar
│   OpenModsLib-1.12.2-0.12.2.jar
│   openscreens-1.12.2-1.0.1.jar
│   OpenSecurity-1.12.2-1.0-93.jar
│   oreberries-1.12.x-0.5.0.jar
│   overloadedarmorbar-1.0.4g.jar
│   p455w0rdslib-1.12.2-2.3.161.jar
│   packedup-1.0.30-forge-mc1.12.jar
│   Pam's+HarvestCraft+1.12.2zg.jar
│   particleculling-1.12.2-v1.4.2.jar
│   Patchouli-1.0-23.6.jar
│   PickUpNotifier-v1.1.5-1.12.2.jar
│   Placebo-1.12.2-1.6.1.jar
│   pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar
│   PortalGun-1.12.2-7.1.0.jar
│   portality-1.12.2-1.2.3-15.jar
│   ProjectE-1.12.2-PE1.4.1.jar
│   ProjectRed-1.12.2-4.9.4.120-Base.jar
│   ProjectRed-1.12.2-4.9.4.120-compat.jar
│   ProjectRed-1.12.2-4.9.4.120-fabrication.jar
│   ProjectRed-1.12.2-4.9.4.120-integration.jar
│   ProjectRed-1.12.2-4.9.4.120-lighting.jar
│   ProjectRed-1.12.2-4.9.4.120-mechanical.jar
│   ProjectRed-1.12.2-4.9.4.120-world.jar
│   ProjectVibrantJourneys-1.12.2-1.6.4.jar
│   Psi-r1.1-78.2.jar
│   PTRLib-1.0.5.jar
│   QMD-1.3.1-1.12.2.jar
│   railcraft-12.0.0.jar
│   RandomTP-MC1.12.2-1.3.5.jar
│   rawinput-1.12.2-1.4.2.jar
│   RebornCore-1.12.2-3.19.5-universal.jar
│   RebornStorage-1.12.2-3.3.4.1.jar
│   RecurrentComplex-1.4.8.5.jar
│   RedstoneFlux-1.12-2.1.1.1-universal.jar
│   refinedstorage-1.6.16.jar
│   refinedstoragerequestify-1.12.2-1.0.2-3.jar
│   Rex's-AdditionalStructures-1.12.x(v.2.5.0).jar
│   rftools-1.12-7.73.jar
│   rftoolsctrl-1.12-2.0.2.jar
│   rftoolsdim-1.12-5.71.jar
│   rftoolspower-1.12-1.2.0.jar
│   rftpwr_oc-0.2.jar
│   RLArtifacts-1.1.2.jar
│   RLFoliage-MC1.12-2.4.1.jar
│   RoguelikeDungeonsFnarEdition-1.12.2-2.4.4.jar
│   RoughlyEnoughIDs-2.1.1.jar
│   roughmobsrevamped-1.12.2-2.3.23.jar
│   rsgauges-1.12.2-1.2.8.jar
│   rustic-1.1.7.jar
│   SCP Lockdown-1.12.2-2.4.2-release.jar
│   sevendaystomine-1.12.2-1.0.3.1.jar.disabled
│   SGExtraParts-1.12.2-1.4.6-49.jar
│   shipwrecks-mc1.12.2-2.0.0.jar
│   SilentGear-1.12.2-0.6.7+76.jar
│   SilentLib-1.12.2-3.0.14+168.jar
│   SilentsGems-1.12.2-2.8.22+327.jar
│   SnowRealMagic-1.12.2-0.7.1.jar
│   SolarFluxReborn-1.12.2-12.4.11.jar
│   SoManyEnchantments-0.5.5.jar
│   sonarcore-1.12.2-5.0.19-20.jar
│   Soviet+Era+0.6.jar
│   SpaceAmbient-1.12.2-0.0.1.jar
│   StevesCarts-1.12.2-2.4.32.137.jar
│   supermartijn642configlib-1.1.8-forge-mc1.12.jar
│   Sync-1.12.2-7.1.0.jar
│   TamModized-1.12.2-0.15.6.jar
│   tc6aspects4jei-0.0.2a.jar
│   techguns-1.12.2-2.0.2.0_pre3.2.jar
│   TenshiLib-1.12.2-1.2.4.jar
│   tesla-core-lib-1.12.2-1.0.18.jar
│   Thaumcraft-1.12.2-6.1.BETA26.jar
│   ThaumicAugmentation-1.12.2-2.1.13.jar
│   the-fifth-world-0.5.1.jar
│   themidnight-0.3.5.jar
│   theoneprobe-1.12-1.4.28.jar
│   ThermalCultivation-1.12.2-0.3.6.1-universal.jar
│   ThermalDynamics-1.12.2-2.5.6.1-universal.jar
│   ThermalExpansion-1.12.2-5.5.7.1-universal.jar
│   ThermalFoundation-1.12.2-2.6.7.1-universal.jar
│   ThermalInnovation-1.12.2-0.3.6.1-universal.jar
│   tombstone-1.12.2-4.6.6.jar
│   trashcans-1.0.18-forge-mc1.12.jar
│   TreeChop-1.12.2-forge-0.14.7.jar
│   Trinity-1.4.b.jar
│   Trinkets and Baubles-32.4.jar
│   trumpetskeleton-1.12-1.0.2.1.jar
│   twilightforest-1.12.2-3.11.1021-universal.jar
│   UniversalModCore-1.12.2-forge-1.2.1.jar
│   UniversalTweaks-1.12.2-1.10.0.jar
│   valkyrielib-1.12.2-2.0.20.1.jar
│   vehicle-mod-0.44.1-1.12.2.jar
│   vintagefix-0.4.2.jar
│   VoidCraft-1.12-0.26.10.jar
│   Waystones_1.12.2-4.1.0.jar
│   Weather2Remastered-1.12.2-2.8.11.jar
│   webdisplays-1.12.2-1.1.jar
│   World-Stripper-1.5.1-1.12.2.jar
│   xercapaint-1.12.2-1.3.jar
│   zerocore-1.12.2-0.1.2.9.jar
│   ZombiesAreReal-2.5.1.jar
│   [___MixinCompat-0.8___].jar
│   _supermartijn642corelib-1.1.17-forge-mc1.12.jar
</details>
Well this is pain, idk how to prevent the word wrapping.

**Comment by I2pRandom** [comment]
Ignore this issue, i just realized the server did crash before hand because of a different mod. This just spit out and error at the end of the log for some reason.
